# Generated by Django 4.2.3 on 2023-07-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_domen_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='domen',
        ),
        migrations.RemoveField(
            model_name='book',
            name='naziv',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[(1, 'Fantastika'), (2, 'Gotički roman'), (3, 'Horor'), (4, 'Pustolovni roman'), (5, 'Romantizam'), (6, 'Saga'), (7, 'Vestern'), (8, 'Žanr kriminalistike')], default=0, max_length=32),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
