# Generated by Django 4.1.4 on 2023-07-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_book_domen_remove_book_naziv_book_genre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domen',
            new_name='Genre',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('0', 'no domens')], max_length=32, null=True),
        ),
    ]
