# Generated by Django 4.1.4 on 2023-07-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_datum_cart_date_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date_now',
        ),
    ]
