# Generated by Django 4.1.4 on 2023-07-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_cart_date_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_now',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
