# Generated by Django 4.1.4 on 2023-07-22 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cart_date_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
