# Generated by Django 4.1.4 on 2023-07-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_publisher_remove_book_review_genre_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='books',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='books',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='book',
        ),
    ]
