# Generated by Django 4.1.4 on 2023-07-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_cart_books_remove_reservations_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='writer',
        ),
    ]
