# Generated by Django 4.1.4 on 2023-07-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_book_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(to='api.book'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='books',
            field=models.ManyToManyField(to='api.book'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.book'),
        ),
    ]
