# Generated by Django 4.2.3 on 2023-07-22 18:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_book_description_alter_publisher_about_them_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='about_them',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='writer',
            name='about_them',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
