# Generated by Django 4.2.3 on 2023-07-22 18:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_book_description_alter_publisher_about_them_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
