# Generated by Django 4.1.4 on 2023-07-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_writer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='date_of_death',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
