# Generated by Django 4.1.4 on 2023-08-14 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0030_alter_book_publisher_remove_book_writer_book_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='books',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('book', 'user')},
        ),
        migrations.AlterIndexTogether(
            name='review',
            index_together={('book', 'user')},
        ),
        migrations.AddField(
            model_name='reservation',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.book'),
        ),
    ]
