# Generated by Django 4.1.4 on 2023-08-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
