# Generated by Django 4.1.4 on 2023-08-27 10:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
