# Generated by Django 4.1.4 on 2023-08-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image'),
        ),
    ]
